# Generated by Django 3.1.7 on 2021-02-27 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210227_1808'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
